### ISSUE TITLE
the "list" function was deprecated in Terraform v0.12

### ISSUE THREAD

**Issue by peritz** [nccgroup/sadcloud#22]
The "list" function used in the s3 and cloudtrail main.tf files was deprecated in Terraform v0.12:

![image](https://user-images.githubusercontent.com/31480556/125073494-f3dc4900-e0b3-11eb-908d-760e55e51b00.png)

The tolist function should be used instead to write the lists.

This was run on Terraform v1.0.2 amd64

**Comment by ramimac** [comment]
@ryanharrison554 just merged @danielperez660's PR fixing this bug - https://github.com/nccgroup/sadcloud/pull/21
